import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { poppins } from "@/lib/fonts";
import SaveUserData from "@/components/Auth/SaveUserToSanity";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}`}
      >
        <ClerkProvider>

          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
